version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: react_app
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: node_api
    volumes:
      - ./backend:/usr/src/app
    ports:
      - '5000:5000'
    networks:
      - app-network
    depends_on:
      - mongo

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - frontend
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge