version: '3.8'

services:
  # ----------------------------------------------------------------
  # Все что касается фронта
  # ----------------------------------------------------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    container_name: react_app
    working_dir: /app
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - API_PREFIX=/api
    networks:
      - app-network

  # ----------------------------------------------------------------
  # Все что касается Общего бэкенда
  # ----------------------------------------------------------------
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    container_name: node_api
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - '5000:5000'
    networks:
      - app-network
    environment:
      - MONGO_URI=mongodb://username:password@mongo:27017/db
      - NODE_PORT=5000
      - NODE_ENV=development
    depends_on:
      - mongo

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/dev/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html  # Копируем собранные файлы для Nginx
    ports:
      - '80:80'
    depends_on:
      - frontend
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: username  # Ваш кастомный пользователь
      MONGO_INITDB_ROOT_PASSWORD: password  # Пароль для пользователя
      MONGO_INITDB_DATABASE: db             # База данных по умолчанию
    networks:
      - app-network
  # ----------------------------------------------------------------

volumes:
  mongo_data:
  auth_mongo_data:
  node_modules: {}

networks:
  app-network:
    driver: bridge